# Generated by Django 3.0.4 on 2020-03-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_group',
        ),
    ]
